/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StatsSplatRouteImport } from './routes/stats.$'
import { Route as WishlistConfirmRouteImport } from './routes/wishlist.confirm'
import { Route as ApiWishlistConfirmRouteImport } from './routes/api.wishlist.confirm'
import { Route as ApiWishlistSubscribeRouteImport } from './routes/api.wishlist.subscribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsSplatRoute = StatsSplatRouteImport.update({
  id: '/stats/$',
  path: '/stats/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistConfirmRoute = WishlistConfirmRouteImport.update({
  id: '/wishlist/confirm',
  path: '/wishlist/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWishlistConfirmRoute = ApiWishlistConfirmRouteImport.update({
  id: '/api/wishlist/confirm',
  path: '/api/wishlist/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWishlistSubscribeRoute = ApiWishlistSubscribeRouteImport.update({
  id: '/api/wishlist/subscribe',
  path: '/api/wishlist/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/privacy': typeof PrivacyRoute
  '/stats/$': typeof StatsSplatRoute
  '/wishlist/confirm': typeof WishlistConfirmRoute
  '/api/wishlist/confirm': typeof ApiWishlistConfirmRoute
  '/api/wishlist/subscribe': typeof ApiWishlistSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/privacy': typeof PrivacyRoute
  '/stats/$': typeof StatsSplatRoute
  '/wishlist/confirm': typeof WishlistConfirmRoute
  '/api/wishlist/confirm': typeof ApiWishlistConfirmRoute
  '/api/wishlist/subscribe': typeof ApiWishlistSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/privacy': typeof PrivacyRoute
  '/stats/$': typeof StatsSplatRoute
  '/wishlist/confirm': typeof WishlistConfirmRoute
  '/api/wishlist/confirm': typeof ApiWishlistConfirmRoute
  '/api/wishlist/subscribe': typeof ApiWishlistSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/privacy'
    | '/stats/$'
    | '/wishlist/confirm'
    | '/api/wishlist/confirm'
    | '/api/wishlist/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/privacy'
    | '/stats/$'
    | '/wishlist/confirm'
    | '/api/wishlist/confirm'
    | '/api/wishlist/subscribe'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/privacy'
    | '/stats/$'
    | '/wishlist/confirm'
    | '/api/wishlist/confirm'
    | '/api/wishlist/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  PrivacyRoute: typeof PrivacyRoute
  StatsSplatRoute: typeof StatsSplatRoute
  WishlistConfirmRoute: typeof WishlistConfirmRoute
  ApiWishlistConfirmRoute: typeof ApiWishlistConfirmRoute
  ApiWishlistSubscribeRoute: typeof ApiWishlistSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/$': {
      id: '/stats/$'
      path: '/stats/$'
      fullPath: '/stats/$'
      preLoaderRoute: typeof StatsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist/confirm': {
      id: '/wishlist/confirm'
      path: '/wishlist/confirm'
      fullPath: '/wishlist/confirm'
      preLoaderRoute: typeof WishlistConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wishlist/confirm': {
      id: '/api/wishlist/confirm'
      path: '/api/wishlist/confirm'
      fullPath: '/api/wishlist/confirm'
      preLoaderRoute: typeof ApiWishlistConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wishlist/subscribe': {
      id: '/api/wishlist/subscribe'
      path: '/api/wishlist/subscribe'
      fullPath: '/api/wishlist/subscribe'
      preLoaderRoute: typeof ApiWishlistSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  PrivacyRoute: PrivacyRoute,
  StatsSplatRoute: StatsSplatRoute,
  WishlistConfirmRoute: WishlistConfirmRoute,
  ApiWishlistConfirmRoute: ApiWishlistConfirmRoute,
  ApiWishlistSubscribeRoute: ApiWishlistSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
